"""add mezcla_id to user_material_overrides

Revision ID: 432a537b0c02
Revises: a1b2c3d4e5f6
Create Date: 2026-06-11 19:03:12.418946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '432a537b0c02'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cache_entries', 'value',
               existing_type=sa.VARCHAR(length=5000),
               type_=sa.Text(),
               existing_nullable=False)
    op.add_column('user_material_overrides', sa.Column('mezcla_id', sa.String(length=100), nullable=True, server_default=''))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_material_overrides', 'mezcla_id')
    op.alter_column('cache_entries', 'value',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=5000),
               existing_nullable=False)
    # ### end Alembic commands ###
