"""Initial migration

Revision ID: 9f0da88b357d
Revises: 
Create Date: 2026-06-11 08:38:47.504500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f0da88b357d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cache_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('value', sa.String(length=5000), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cache_entries_expires_at'), 'cache_entries', ['expires_at'], unique=False)
    op.create_index(op.f('ix_cache_entries_key'), 'cache_entries', ['key'], unique=True)
    op.create_table('insumos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=False),
    sa.Column('un', sa.String(length=50), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('categoria', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pagos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('payment_link', sa.String(length=30), nullable=False),
    sa.Column('url', sa.String(length=200), nullable=False),
    sa.Column('reference', sa.String(length=60), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('transaction_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_link')
    )
    op.create_index(op.f('ix_pagos_reference'), 'pagos', ['reference'], unique=True)
    op.create_index(op.f('ix_pagos_usuario_id'), 'pagos', ['usuario_id'], unique=False)
    op.create_table('productos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=False),
    sa.Column('unidad', sa.String(length=50), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('valor_anterior', sa.Float(), nullable=True),
    sa.Column('origen', sa.String(length=20), nullable=True),
    sa.Column('categoria', sa.String(length=200), nullable=True),
    sa.Column('n01', sa.String(length=200), nullable=True),
    sa.Column('n02', sa.String(length=200), nullable=True),
    sa.Column('n03', sa.String(length=200), nullable=True),
    sa.Column('proveedor', sa.String(length=200), nullable=True),
    sa.Column('descripcion_ajustada', sa.String(length=500), nullable=True),
    sa.Column('tienda', sa.String(length=200), nullable=False),
    sa.Column('url_origen', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo', 'tienda', name='uq_producto_codigo_tienda')
    )
    op.create_index(op.f('ix_productos_codigo'), 'productos', ['codigo'], unique=False)
    op.create_table('rate_limits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('window_start', sa.DateTime(), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rate_limits_key'), 'rate_limits', ['key'], unique=False)
    op.create_index(op.f('ix_rate_limits_window_start'), 'rate_limits', ['window_start'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('token', sa.String(length=200), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('plan', sa.String(length=10), nullable=True),
    sa.Column('fecha_pago', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('uso_calculos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uso_calculos_usuario_id'), 'uso_calculos', ['usuario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_uso_calculos_usuario_id'), table_name='uso_calculos')
    op.drop_table('uso_calculos')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_rate_limits_window_start'), table_name='rate_limits')
    op.drop_index(op.f('ix_rate_limits_key'), table_name='rate_limits')
    op.drop_table('rate_limits')
    op.drop_index(op.f('ix_productos_codigo'), table_name='productos')
    op.drop_table('productos')
    op.drop_index(op.f('ix_pagos_usuario_id'), table_name='pagos')
    op.drop_index(op.f('ix_pagos_reference'), table_name='pagos')
    op.drop_table('pagos')
    op.drop_table('insumos')
    op.drop_index(op.f('ix_cache_entries_key'), table_name='cache_entries')
    op.drop_index(op.f('ix_cache_entries_expires_at'), table_name='cache_entries')
    op.drop_table('cache_entries')
    # ### end Alembic commands ###
