@echo off
echo [PROD] Cargando entorno de produccion...
copy /Y config\.env.production .env >nul
echo [PROD] Iniciando servidor en produccion...
uvicorn app.main:app --host 0.0.0.0 --port %PORT% --workers 2 --timeout-keep-alive 30 --limit-concurrency 100
